### ISSUE TITLE
python3 AttributeError: 'module' object has no attribute 'HTTPSConnection'

### ISSUE THREAD

**Issue by gclsoft** [OKCoin/rest#4]
```
def httpGet(url,resource,params=''):
    conn = http.client.HTTPSConnection(url, timeout=10)
```

```
pydev debugger: starting
 现货行情 
Traceback (most recent call last):
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/pydevd.py", line 1479, in <module>
    debugger.run(setup['file'], None, None)
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/pydevd.py", line 1125, in run
    pydev_imports.execfile(file, globals, locals)  #execute the script
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/_pydev_execfile.py", line 38, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) #execute the script
  File "/Users/apple/node/undo4096/tool/videoPei/btc/Client.py", line 21, in <module>
    print (okcoinSpot.ticker('btc_usd'))
  File "/Users/apple/node/undo4096/tool/videoPei/btc/OkcoinSpotAPI.py", line 19, in ticker
    return httpGet(self.__url,TICKER_RESOURCE,params)
  File "/Users/apple/node/undo4096/tool/videoPei/btc/HttpMD5Util.py", line 19, in httpGet
    conn = http.client.HTTPSConnection(url, timeout=10)
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```

**Comment by karsbin** [comment]
use python3.xx
